import PlanningTree from './PlanningTree';
import BatchCreate from './BatchCreate';
import type { BatchKind } from './batch';
import Select from './Select';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, ArchiveRestore, CalendarDays, ChevronLeft, ChevronRight, CircleHelp, FolderKanban, History as HistoryIcon, LayoutDashboard, Plus, RotateCcw, Save, Settings2, Target, Trash2 } from 'lucide-react';
import { open, save } from '@tauri-apps/plugin-dialog';
import CalendarOverview from './CalendarOverview';
import { calendarTaskChoices, calendarTaskPlacement } from './calendarWeekTask';
import HistoryPage from './History';
import { addDays, annualGoalTasks, assignmentInWeek, assignmentsForDate, calendarRange, categoryTotals, cycleWeek, dayTaskProjectId, dayTaskTaskId, dayTaskTimeLabel, formatHours, id, localDate, minuteLabel, parseMinute, progress, shiftCalendarDate, STATUS, validateTimeEntry, weekStart, type CalendarMode, type Data, type Status, type Task } from './model';
import { batchCreate, deleteCycleRecord, deleteDirectionRecord, addAssignmentWeek, generateRecurrences, initDb, insert, listBackups, manualBackup, readData, remove, removeAnnualGoal, removeAssignmentWeek, removePlanBlock, removePlanningItem, stageRestore, update, updateDayTask } from './db';

type Page = 'home'|'cycles'|'tasks'|'calendar'|'reports'|'history'|'settings';
type FormKind = 'cycle'|'direction'|'annual'|'task'|'assignment'|'dayTask'|'plan'|'dailyPlan'|'entry'|'category'|'recurrence';
type FormState = { kind:FormKind; values:Record<string,string>; editingId?:string };
type CreateFn = (kind:FormKind, values?:Record<string,string>, editingId?:string)=>void;
type DeleteFn = (kind:'task'|'assignment'|'dayTask', rowId:string, title:string)=>void;
const now = () => new Date().toISOString();
const fmtDate = (s:string) => s.slice(5).replace('-','/');
const H = ({children, action}:{children:React.ReactNode;action?:React.ReactNode}) => <div className="section-head"><h2>{children}</h2>{action}</div>;
const StatusSelect = ({value,onChange}:{value:Status;onChange:(s:Status)=>void}) => <Select className={`status ${value}`} value={value} onChange={e=>onChange(e.target.value as Status)}>{Object.entries(STATUS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</Select>;
const Pill = ({status}:{status:Status}) => <span className={`pill ${status}`}>{STATUS[status]}</span>;
const Progress = ({items}:{items:Task[]}) => { const p=progress(items); return p ? <div className="progress"><div className="progress-track"><i style={{width:`${p.percent}%`}} /></div><strong>{p.percent}%</strong><span>{p.done}/{p.total} 项完成</span></div> : <span className="muted">暂无进度</span>; };
const Empty = ({text,onClick,button}:{text:string;onClick?:()=>void;button?:string}) => <div className="empty"><CircleHelp size={22}/><span>{text}</span>{onClick&&<button className="text-button" onClick={onClick}>{button||'新建'}</button>}</div>;

export default function App() {
  const [data,setData]=useState<Data|null>(null), [page,setPage]=useState<Page>('home'), [date,setDate]=useState(localDate()), [calendarMode,setCalendarMode]=useState<CalendarMode>('week'), [form,setForm]=useState<FormState|null>(null);
  const [selectedCycle,setSelectedCycle]=useState<string|null>(null), [focusedTaskId,setFocusedTaskId]=useState<string|null>(null), [reportMode,setReportMode]=useState<'day'|'week'|'month'>('month');
  const [batch,setBatch]=useState<{kind:BatchKind;defaults:Record<string,string>}|null>(null);
  const [annualYear,setAnnualYear]=useState(new Date().getFullYear());
  const [message,setMessage]=useState(''), [busy,setBusy]=useState(false), [backups,setBackups]=useState<string[]>([]);
  const refresh=useCallback(async(focusDate=localDate())=>{ const next=await readData(); await generateRecurrences(next,focusDate); setData(await readData()); },[]);
  useEffect(()=>{ initDb().then(()=>refresh(date)).catch(e=>setMessage(`数据库启动失败：${String(e)}`)); },[refresh]);
  useEffect(()=>{ if(data) refresh(date).catch(e=>setMessage(String(e))); },[date]);
  const mutate=async(fn:()=>Promise<unknown>,success='已保存')=>{ setBusy(true); setMessage('正在保存到本地数据库…'); try { await fn(); setMessage('正在刷新工作台…'); await refresh(date); setForm(null); setMessage(success); } catch(e) { setMessage(`操作失败：${String(e)}`); } finally {setBusy(false);} };
  const create=(kind:FormKind,values:Record<string,string>={},editingId?:string)=>{setMessage('');setForm({kind,values,editingId});};
  const editDayTask=(task:Data['dayTasks'][number])=>{const start=task.scheduled_start_at?new Date(task.scheduled_start_at):null,end=task.scheduled_end_at?new Date(task.scheduled_end_at):null;create('dayTask',{date:task.date,title:task.title,assignment_id:task.assignment_id||'',start:start?minuteLabel(start.getHours()*60+start.getMinutes()):'',end:end?minuteLabel(end.getHours()*60+end.getMinutes()):'',category_id:task.scheduled_category_id||''},task.id)};
  const deletePlanning=(kind:'task'|'assignment'|'dayTask',rowId:string,title:string)=>{
    if(!data)return;
    const linked=kind==='task' ? `${data.assignments.filter(a=>a.task_id===rowId).length} 个周任务会删除；关联日任务和时间记录会保留。` : kind==='assignment' ? `该周任务在全部周次的安排会一并删除；${data.dayTasks.filter(t=>t.assignment_id===rowId).length} 个日任务会保留并解除周关联，实际记录会保留。` : '关联的计划时段和实际时间记录会保留并解除关联。';
    if(confirm(`删除“${title}”？\n${linked}\n此操作无法撤销。`)) mutate(()=>removePlanningItem(kind,rowId),'已删除');
  };
  const scheduleAssignment=(assignmentId:string,weekNo:number)=>mutate(()=>addAssignmentWeek(assignmentId,weekNo),'已安排到周次');
  const unscheduleAssignment=(assignmentId:string,weekNo:number)=>mutate(()=>removeAssignmentWeek(assignmentId,weekNo),'已移回待办池，原有日任务关联已保留');
  const editPlan=(p:Data['planBlocks'][number])=>setForm({kind:'plan',editingId:p.id,values:{date:p.date,start:minuteLabel(p.start_min),end:minuteLabel(p.end_min),title:p.title,day_task_id:p.day_task_id||''}});
  const editDailyPlan=(p:Data['dailyPlanTemplates'][number])=>setForm({kind:'dailyPlan',editingId:p.id,values:{start:minuteLabel(p.start_min),end:minuteLabel(p.end_min),title:p.title}});
  const editEntry=(e:Data['timeEntries'][number])=>{const start=new Date(e.start_at),end=new Date(e.end_at);setForm({kind:'entry',editingId:e.id,values:{date:localDate(start),start:minuteLabel(start.getHours()*60+start.getMinutes()),end:minuteLabel(end.getHours()*60+end.getMinutes()),title:e.title,category_id:e.category_id,day_task_id:e.day_task_id||''}})};
  const setStatus=(table:string,rowId:string,status:Status)=>mutate(()=>update(table,rowId,{status}),'状态已更新');
  const deleteDirection=(directionId:string,title:string)=>{
    const count=data?.annualGoals.filter(goal=>goal.direction_id===directionId).length||0;
    if(confirm(`删除年度方向“${title}”？${count} 个年度目标及其下层任务会保留，并解除方向归属。`))mutate(()=>deleteDirectionRecord(directionId),'方向已删除，年度目标已保留');
  };
  const deleteCycle=(cycleId:string)=>{
    if(!data)return;const item=data.cycles.find(c=>c.id===cycleId);if(!item)return;
    const tasks=data.tasks.filter(t=>t.cycle_id===cycleId),weeks=data.assignments.filter(a=>a.cycle_id===cycleId),days=data.dayTasks.filter(d=>weeks.some(w=>w.id===d.assignment_id)||tasks.some(t=>t.id===d.task_id));
    if(confirm(`删除周期“${item.title}”？\n${tasks.length} 个本轮待办、${weeks.length} 个周任务及 ${days.length} 个日任务会保留。周期归属解除，周次安排清空，实际记录保留。`))mutate(async()=>{await deleteCycleRecord(cycleId);setSelectedCycle(data.cycles.filter(c=>c.id!==cycleId).sort((a,b)=>b.start_date.localeCompare(a.start_date))[0]?.id||'__unassigned');},'周期已删除，任务已保留');
  };
  const deleteAnnual=(annualId:string,title:string)=>{
    const annual=data?.annualGoals.find(g=>g.id===annualId);
    if(!data||!annual)return;
    const linked=annualGoalTasks(data,annual).length;
    if(confirm(`删除年度目标“${title}”？\n${linked} 个关联待办会保留，并显示为未关联年度目标。\n此操作无法撤销。`)) mutate(()=>removeAnnualGoal(annualId),'年度目标已删除，关联待办已保留');
  };
  const toggleAnnual=(annual:Data['annualGoals'][number])=>mutate(()=>update('annual_goals',annual.id,{completed:annual.completed===1?0:1}),'年度目标状态已更新');
  const cycle = selectedCycle==='__unassigned'?undefined:data?.cycles.find(c=>c.id===selectedCycle) || data?.cycles.slice().sort((a,b)=>b.start_date.localeCompare(a.start_date))[0];
  const currentWeek = cycle ? cycleWeek(cycle,localDate()) : 0;
  const nav:[Page,string,React.ReactNode][]=[['home','总览',<LayoutDashboard size={18}/>],['cycles','12 周计划',<Target size={18}/>],['tasks','本轮待办',<FolderKanban size={18}/>],['calendar','日程',<CalendarDays size={18}/>],['reports','复盘统计',<Activity size={18}/>],['history','历史情况',<HistoryIcon size={18}/>],['settings','设置与备份',<Settings2 size={18}/>]];
  const focusTask=(taskId:string)=>{if(!data?.tasks.some(t=>t.id===taskId)){setMessage('该本轮待办已不存在');return;}setFocusedTaskId(taskId);setPage('tasks');};
  useEffect(()=>{if(page==='tasks'&&focusedTaskId) requestAnimationFrame(()=>{const element=document.getElementById(`task-${focusedTaskId}`);element?.scrollIntoView({block:'center'});element?.classList.add('task-highlight');setTimeout(()=>element?.classList.remove('task-highlight'),3000);});},[page,focusedTaskId,data]);

  const openBatch=(kind:BatchKind,defaults:Record<string,string>={})=>setBatch({kind,defaults});
  const editNode=(kind:BatchKind,rowId:string)=>{
    if(!data)return;
    if(kind==='direction'){const row=data.directions.find(x=>x.id===rowId);if(row)create(kind,{title:row.title},rowId);}
    if(kind==='annual'){const row=data.annualGoals.find(x=>x.id===rowId);if(row)create(kind,{title:row.title,year:String(row.year),direction_id:row.direction_id||''},rowId);}
    if(kind==='task'){const row=data.tasks.find(x=>x.id===rowId);if(row)create(kind,{title:row.title,annual_goal_id:row.annual_goal_id||'',cycle_id:row.cycle_id||'',due_date:row.due_date||''},rowId);}
    if(kind==='assignment'){const row=data.assignments.find(x=>x.id===rowId);if(row)create(kind,{task_id:row.task_id,cycle_id:row.cycle_id||'',commitment:row.commitment,review:row.review},rowId);}
    if(kind==='dayTask'){const row=data.dayTasks.find(x=>x.id===rowId);if(row)editDayTask(row);}
  };
  const deleteNode=(kind:BatchKind,rowId:string,title:string)=>kind==='direction'?deleteDirection(rowId,title):kind==='annual'?deleteAnnual(rowId,title):deletePlanning(kind,rowId,title);

  async function submitForm() {
    if (!form || !data) return;
    const v=form.values, stamp=now(), uid=id();
    const required=(...keys:string[])=>{ for(const key of keys) if(!v[key]?.trim()) throw Error(`请填写${fieldLabel(key)}`); };
    try {
      if(form.kind==='cycle') { required('title','start_date'); const original=data.cycles.find(c=>c.id===form.editingId);if(original&&original.start_date!==v.start_date&&!confirm('周次对应日期将变化，日任务及实际记录日期保持原样。继续保存吗？'))return;await mutate(()=>form.editingId?update('cycles',form.editingId,{title:v.title.trim(),start_date:v.start_date}):insert('cycles',{id:uid,title:v.title.trim(),start_date:v.start_date,created_at:stamp}));if(!form.editingId)setSelectedCycle(uid); }
      if(form.kind==='direction') { required('title'); await mutate(()=>form.editingId?update('directions',form.editingId,{title:v.title.trim()}):insert('directions',{id:uid,title:v.title.trim(),created_at:stamp})); }
      if(form.kind==='annual') { required('title','year');if(!form.editingId)required('direction_id');if(!Number.isInteger(Number(v.year))||Number(v.year)<1||Number(v.year)>9999)throw Error('请填写有效年份');const values={title:v.title.trim(),direction_id:v.direction_id||null,year:Number(v.year)};await mutate(()=>form.editingId?update('annual_goals',form.editingId,values):insert('annual_goals',{id:uid,...values,completed:0,created_at:stamp})); }
      if(form.kind==='task') { required('title');if(!form.editingId)required('cycle_id','annual_goal_id'); if(form.editingId && data.assignments.some(a=>a.task_id===form.editingId&&a.cycle_id!==v.cycle_id&&data.assignmentWeeks.some(w=>w.assignment_id===a.id))) throw Error('已有周次安排的待办不能直接更换周期，请先移除周次'); const values={title:v.title.trim(),cycle_id:v.cycle_id||null,annual_goal_id:v.annual_goal_id||null,due_date:v.due_date||null}; await mutate(()=>form.editingId?update('tasks',form.editingId,values):insert('tasks',{id:uid,...values,cycle_goal_id:null,project_id:null,status:'todo',created_at:stamp})); }
      if(form.kind==='assignment') { required('task_id','commitment');const parent=data.tasks.find(t=>t.id===v.task_id);if(!parent)throw Error('所选本轮待办不存在');if(!parent.cycle_id&&!form.editingId)throw Error('请先为本轮待办指定周期');const values={task_id:v.task_id,cycle_id:parent.cycle_id,commitment:v.commitment.trim(),review:v.review||''}; if(v.calendar_date&&!form.editingId){
          const placement=calendarTaskPlacement(data,parent.id,v.calendar_date);
          if(!placement)throw Error('所选待办所属周期不覆盖正在查看的周，请重新选择');
          if(!calendarTaskChoices(data,v.calendar_date,v.direction_id,v.annual_goal_id).some(item=>item.id===parent.id))throw Error('所选待办与年度方向、年度目标不一致，请重新选择');
          await mutate(()=>batchCreate('assignment',[{values:{id:uid,...values,status:'todo',created_at:stamp},weeks:[placement.week]}]),'周任务已创建并安排到查看周');
        }else await mutate(()=>form.editingId?update('week_assignments',form.editingId,values):insert('week_assignments',{id:uid,...values,status:'todo',created_at:stamp})); }
      if(form.kind==='dayTask') {
        required('date'); if(!v.title?.trim()) throw Error('请填写具体内容');
        const assignment=data.assignments.find(a=>a.id===v.assignment_id); if(v.assignment_id&&!assignment) throw Error('所选周任务不存在，请重新选择');
        const original=form.editingId?data.dayTasks.find(item=>item.id===form.editingId):null;
        if(assignment&&!assignmentsForDate(data,v.date).some(a=>a.id===assignment.id)&&!(original?.assignment_id===assignment.id&&original.date===v.date)) throw Error('该周任务未安排在日任务日期所在周，请重新选择');
        const task=data.tasks.find(t=>t.id===assignment?.task_id), hasTime=Boolean(v.start||v.end||v.category_id);
        let scheduledStart:string|null=null, scheduledEnd:string|null=null;
        if(hasTime) {
          if(!v.start||!v.end||!v.category_id) throw Error('填写具体时间时，请同时填写开始时间、结束时间和时间分类');
          if(v.start===v.end) throw Error('开始时间和结束时间不能相同');
          if(!data.categories.some(c=>c.id===v.category_id)) throw Error('所选时间分类不存在');
          const start=new Date(`${v.date}T${v.start}:00`),end=new Date(`${v.date}T${v.end}:00`);
          if(end<start) end.setDate(end.getDate()+1);
          if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())) throw Error('请填写有效的具体时间');
          scheduledStart=start.toISOString(); scheduledEnd=end.toISOString();
          if(!form.editingId) {const conflict=validateTimeEntry(data.timeEntries,scheduledStart,scheduledEnd);if(conflict) throw Error(conflict);}
        }
        const values={date:v.date,title:v.title.trim(),assignment_id:assignment?.id||null,project_id:task?.project_id||null,task_id:task?.id||null,scheduled_start_at:scheduledStart,scheduled_end_at:scheduledEnd,scheduled_category_id:hasTime?v.category_id:null};
        await mutate(()=>form.editingId?updateDayTask(form.editingId,values):insert('day_tasks',{id:uid,...values,status:'todo',recurrence_id:null,created_at:stamp}));
      }
      if(form.kind==='plan') { required('date','title','start','end'); const start=parseMinute(v.start),end=parseMinute(v.end); if(end<=start) throw Error('结束时间必须晚于开始时间'); const values={date:v.date,start_min:start,end_min:end,title:v.title.trim(),day_task_id:v.day_task_id||null}; await mutate(()=>form.editingId?update('plan_blocks',form.editingId,values):insert('plan_blocks',{id:uid,...values,recurrence_id:null,created_at:stamp})); }
      if(form.kind==='dailyPlan') { required('title','start','end'); const start=parseMinute(v.start),end=parseMinute(v.end); if(start<0||end>1440||end<=start) throw Error('请填写 00:00—24:00 内有效的时间段'); const values={start_min:start,end_min:end,title:v.title.trim()}; await mutate(()=>form.editingId?update('daily_plan_templates',form.editingId,values):insert('daily_plan_templates',{id:uid,...values,created_at:stamp})); }
      if(form.kind==='entry') { required('date','start','end','category_id'); if(v.start===v.end) throw Error('开始和结束时间不能相同'); const start=new Date(`${v.date}T${v.start}:00`),end=new Date(`${v.date}T${v.end}:00`); if(end<start) end.setDate(end.getDate()+1); const error=validateTimeEntry(data.timeEntries,start.toISOString(),end.toISOString(),form.editingId); if(error) throw Error(error); const dayTask=data.dayTasks.find(t=>t.id===v.day_task_id); if(v.day_task_id&&!dayTask) throw Error('所选日任务不存在，请重新选择'); const task=data.tasks.find(t=>t.id===(dayTask?dayTaskTaskId(data,dayTask):null)); const values={start_at:start.toISOString(),end_at:end.toISOString(),title:v.title?.trim()||'',category_id:v.category_id,day_task_id:dayTask?.id||null,project_id:task?.project_id||(dayTask?dayTaskProjectId(data,dayTask):null),task_id:task?.id||null}; await mutate(()=>form.editingId?update('time_entries',form.editingId,values):insert('time_entries',{id:uid,...values,created_at:stamp})); }
      if(form.kind==='category') { required('name'); await mutate(()=>insert('categories',{id:uid,name:v.name.trim(),color:v.color||'#557cb2',created_at:stamp})); }
      if(form.kind==='recurrence') { required('kind','frequency','title','start_date'); if(v.kind==='plan' && (!v.start||!v.end||parseMinute(v.end)<=parseMinute(v.start))) throw Error('请填写有效的时间段'); await mutate(()=>insert('recurrences',{id:uid,kind:v.kind,frequency:v.frequency,weekdays:v.frequency==='weekly'?(v.weekdays||String(new Date(`${v.start_date}T12:00:00`).getDay())):'',start_date:v.start_date,end_date:v.end_date||null,title:v.title.trim(),start_min:v.kind==='plan'?parseMinute(v.start):null,end_min:v.kind==='plan'?parseMinute(v.end):null,project_id:data.tasks.find(t=>t.id===v.task_id)?.project_id||null,task_id:v.task_id||null,category_id:null,active:1,created_at:stamp})); }
    } catch(e) { setMessage(String(e)); }
  }
  function fieldLabel(key:string) { return ({title:'标题',start_date:'开始日期',date:'日期',direction_id:'年度方向',year:'年份',cycle_id:'12 周周期',annual_goal_id:'年度目标',task_id:'本轮待办',week_no:'周次',commitment:'本周承诺',start:'开始时间',end:'结束时间',category_id:'分类',name:'分类名称',kind:'重复类型',frequency:'重复频率'} as Record<string,string>)[key]||key; }
  const formFields=useMemo(()=>{
    if(!form)return [];
    const fields=fieldsFor(form.kind,data,form.values.cycle_id||cycle?.id,form.values.date||date);
    if(form.kind==='assignment'&&form.values.calendar_date&&data){
      const v=form.values;
      const goals=data.annualGoals.filter(goal=>!v.direction_id||goal.direction_id===v.direction_id);
      fields.unshift({name:'direction_id',label:'年度方向（筛选，可选）',type:'select',options:data.directions.map(item=>[item.id,item.title])},{name:'annual_goal_id',label:'年度目标（筛选，可选）',type:'select',options:goals.map(item=>[item.id,`${item.year} · ${item.title}`])});
      const field=fields.find(item=>item.name==='task_id');
      if(field)field.options=calendarTaskChoices(data,v.calendar_date,v.direction_id,v.annual_goal_id).map(item=>[item.id,`${data.cycles.find(c=>c.id===item.cycle_id)?.title} · ${data.annualGoals.find(g=>g.id===item.annual_goal_id)?.title||'未归属年度目标'} · ${item.title}`]);
    }
    if(form.kind==='dayTask'&&form.editingId&&data){
      const original=data.dayTasks.find(item=>item.id===form.editingId), field=fields.find(item=>item.name==='assignment_id');
      if(original?.assignment_id&&field&&!field.options?.some(([value])=>value===original.assignment_id)) field.options?.push([original.assignment_id,'原关联周任务（该日期所在周未安排）']);
    }
    return fields;
  },[form,data,cycle?.id,date]);
  const setField=(name:string,value:string)=>setForm(s=>{
    if(!s)return s;
    const values:Record<string,string>={...s.values,[name]:value,...(s.kind==='assignment'&&name==='cycle_id'?{task_id:''}:{}),...(s.kind==='entry'&&name==='date'&&value!==s.values.date?{day_task_id:''}:{})};
    if(s.kind==='assignment'&&s.values.calendar_date){
      if(name==='direction_id'){values.annual_goal_id='';values.task_id='';}
      if(name==='annual_goal_id')values.task_id='';
      if(name==='task_id'){const task=data?.tasks.find(item=>item.id===value),goal=data?.annualGoals.find(item=>item.id===task?.annual_goal_id);values.annual_goal_id=goal?.id||'';values.direction_id=goal?.direction_id||'';}
    }
    return {...s,values};
  });

  const [calendarFrom,calendarTo]=calendarRange(date,calendarMode);
  const calendarTitle=calendarMode==='day'?new Date(`${date}T12:00:00`).toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}):calendarMode==='week'?`${calendarFrom} — ${addDays(calendarTo,-1)}`:calendarMode==='month'?`${Number(date.slice(0,4))} 年 ${Number(date.slice(5,7))} 月`:`${date.slice(0,4)} 年`;

  return <div className="shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark"><span/><span/><span/><span/></div><div><strong>个人工作台</strong><small>把计划变成进展</small></div></div><nav>{nav.map(([key,label,icon])=><button key={key} className={page===key?'active':''} onClick={()=>{setFocusedTaskId(null);if(key==='calendar')setCalendarMode('week');setPage(key)}}>{icon}<span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="today-dot"/>今天是 {localDate()}<span>本地离线</span></div></aside>
    <main className="main"><header className="topbar"><div className="breadcrumb">个人工作台 <span>/</span> {nav.find(n=>n[0]===page)?.[1]}</div><div className="top-actions"><button className="icon-button" onClick={()=>{setDate(localDate());setCalendarMode('week');setPage('calendar')}} title="回到本周"><CalendarDays size={18}/></button><button className="primary small" onClick={()=>create('dayTask',{date:calendarMode==='day'?date:localDate()})}><Plus size={16}/> 新建日任务</button></div></header>
      {message&&<div className="notice" role="status">{message}<button onClick={()=>setMessage('')}>关闭</button></div>}
      {!data ? <div className="loading">正在打开本地工作台…</div> : <div className="content">
        {page==='home'&&<><div className="page-heading"><div><div className="kicker">{new Date().toLocaleDateString('zh-CN',{weekday:'long',month:'long',day:'numeric'})}</div><h1>今天，从最重要的事开始。</h1><p>目标、待办和时间记录都在这里汇合。</p></div><button className="outline" onClick={()=>{setCalendarMode('week');setPage('calendar')}}>打开日程 <ChevronRight size={16}/></button></div>
          <div className="home-grid"><section className="panel"><H action={<button className="text-button" onClick={()=>{setCalendarMode('week');setPage('calendar')}}>查看日程</button>}>今日任务</H>{data.dayTasks.filter(t=>t.date===localDate()).length ? data.dayTasks.filter(t=>t.date===localDate()).map(t=><div className="compact-row" key={t.id}><span className={`state-dot ${t.status}`}/><span>{dayTaskTimeLabel(t)&&<small className="task-clock">{dayTaskTimeLabel(t)} · </small>}{t.title}</span><StatusSelect value={t.status} onChange={s=>setStatus('day_tasks',t.id,s)}/><div className="record-actions"><button onClick={()=>editDayTask(t)}>编辑</button><button onClick={()=>deletePlanning('dayTask',t.id,t.title)}>删除</button></div></div>) : <Empty text="今天还没有任务" onClick={()=>create('dayTask',{date:localDate()})}/>}</section>
            <section className="panel"><H action={<button className="text-button" onClick={()=>setPage('cycles')}>查看周计划</button>}>本周计划</H>{cycle&&currentWeek>=1&&currentWeek<=12&&data.assignments.filter(a=>a.cycle_id===cycle.id&&assignmentInWeek(data,a.id,currentWeek)).length ? data.assignments.filter(a=>a.cycle_id===cycle.id&&assignmentInWeek(data,a.id,currentWeek)).map(a=><div className="commit-row" key={a.id}><Pill status={a.status}/><button onClick={()=>focusTask(a.task_id)}>{a.commitment}</button></div>) : <Empty text="本周还没有安排"/>}<H>逾期待办</H>{data.tasks.filter(t=>t.due_date&&t.due_date<localDate()&&t.status!=='done').slice(0,4).map(t=><div className="commit-row" key={t.id}><span className="late">{t.due_date}</span><button onClick={()=>focusTask(t.id)}>{t.title}</button></div>)}{!data.tasks.some(t=>t.due_date&&t.due_date<localDate()&&t.status!=='done')&&<div className="muted">没有逾期事项</div>}</section></div>
          <div className="home-grid secondary"><section className="panel"><H action={<button className="text-button" onClick={()=>setPage('tasks')}>全部本轮待办</button>}>进行中的本轮待办</H>{data.tasks.filter(t=>t.status==='doing'||t.status==='todo').slice(0,5).length ? data.tasks.filter(t=>t.status==='doing'||t.status==='todo').slice(0,5).map(t=><button className="project-summary" key={t.id} onClick={()=>focusTask(t.id)}><div><strong>{t.title}</strong><span>{data.annualGoals.find(g=>g.id===t.annual_goal_id)?.title||'未关联年度目标'}</span></div><Pill status={t.status}/></button>) : <Empty text="暂无进行中的本轮待办" onClick={()=>create('task',{cycle_id:cycle?.id||''})}/>}</section>
            <section className="panel hero-panel"><div className="eyebrow">当前 12 周周期</div>{cycle?<><h2>{cycle.title}</h2><p>{cycle.start_date} — {addDays(cycle.start_date,83)} · 第 {Math.min(Math.max(cycleWeek(cycle,localDate()),1),12)} 周</p><div className="hero-metrics"><div><strong>{data.tasks.filter(t=>t.cycle_id===cycle.id).length}</strong><span>本轮待办</span></div><div><strong>{data.assignments.filter(a=>a.cycle_id===cycle.id && a.status==='done').length}</strong><span>周计划完成</span></div></div><button className="light-button" onClick={()=>setPage('cycles')}>查看 12 周计划 <ChevronRight size={16}/></button></>:<Empty text="还没有 12 周周期" onClick={()=>create('cycle',{start_date:localDate()})} button="创建周期"/>}</section></div></>}
        {page==='cycles'&&<><div className="page-heading"><div><div className="kicker">计划地图</div><h1>12 周计划</h1><p>年度方向定主题，年度目标定结果，12 周计划承接每一轮行动。</p></div><div className="heading-actions"><Select aria-label="选择12周周期" value={cycle?.id||'__unassigned'} onChange={e=>setSelectedCycle(e.target.value)}><option value="__unassigned">未归属周期</option>{data.cycles.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</Select><button className="primary" onClick={()=>create('cycle',{start_date:localDate()})}><Plus size={16}/> 新周期</button>{cycle&&<><button className="outline" onClick={()=>create('cycle',{title:cycle.title,start_date:cycle.start_date},cycle.id)}>编辑周期</button><button className="outline danger" onClick={()=>deleteCycle(cycle.id)}>删除周期</button></>}</div></div>
          <p className="cycle-dates">{cycle?`${cycle.start_date} — ${addDays(cycle.start_date,83)}`:'未归属周期：重新指定周期后，可继续安排周次'}</p>
          <PlanningTree data={data} cycleId={cycle?.id||null} onCreate={create} onBatch={openBatch} onEdit={editNode} onDelete={deleteNode} onStatus={(kind,id,status)=>setStatus(({task:'tasks',assignment:'week_assignments',dayTask:'day_tasks'} as Record<string,string>)[kind],id,status)} onAnnual={id=>{const row=data.annualGoals.find(a=>a.id===id);if(row)toggleAnnual(row);}}/>
          <AnnualCards data={data} year={annualYear} onYear={setAnnualYear} cycleId={cycle?.id||''} create={create} edit={editNode} deleteAnnual={deleteAnnual} toggleAnnual={toggleAnnual} focusTask={focusTask}/>
          <div className="planning-toolbar"><button onClick={()=>create('direction')}>＋ 年度方向</button><button onClick={()=>create('annual',{year:String(new Date().getFullYear())})}>＋ 年度目标</button><button onClick={()=>create('task',{cycle_id:cycle?.id||''})}>＋ 本轮待办</button><button onClick={()=>create('assignment',{cycle_id:cycle?.id||''})}>＋ 周任务</button></div>
          {<WeekTaskPool data={data} cycleId={cycle?.id||null} create={create} deletePlanning={deletePlanning} schedule={scheduleAssignment} unschedule={unscheduleAssignment} setStatus={setStatus}/>}
          {!cycle?<Empty text="先创建一个 12 周周期" onClick={()=>create('cycle',{start_date:localDate()})}/>:<div className="matrix-wrap"><table className="matrix"><thead><tr><th className="sticky-col">年度方向</th><th className="sticky-goal">年度目标</th><th>本轮待办</th>{Array.from({length:12},(_,i)=><th key={i} className={currentWeek===i+1?'this-week':''}>第 {i+1} 周<small>{fmtDate(weekStart(cycle,i+1))}</small></th>)}</tr></thead><tbody>{data.tasks.filter(t=>t.cycle_id===cycle.id).length ? data.tasks.filter(t=>t.cycle_id===cycle.id).map(t=>{const annual=data.annualGoals.find(a=>a.id===t.annual_goal_id),direction=data.directions.find(d=>d.id===annual?.direction_id);return <tr key={t.id}><td className="sticky-col"><b>{direction?.title||'未关联年度方向'}</b></td><td className="sticky-goal"><strong>{annual?.title||'未关联年度目标'}</strong><small>{annual?.year||''} 年</small><Progress items={annual?annualGoalTasks(data,annual):[]}/></td><td><strong>{t.title}</strong><div className="record-actions"><button onClick={()=>create('task',{title:t.title,cycle_id:t.cycle_id||'',annual_goal_id:t.annual_goal_id||'',due_date:t.due_date||''},t.id)}>编辑</button><button onClick={()=>deletePlanning('task',t.id,t.title)}>删除</button><button onClick={()=>create('assignment',{task_id:t.id,cycle_id:cycle.id})}>＋ 周任务</button></div><Pill status={t.status}/></td>{Array.from({length:12},(_,i)=>{const as=data.assignments.filter(a=>a.cycle_id===cycle.id&&assignmentInWeek(data,a.id,i+1)&&a.task_id===t.id);return <td key={i} className={currentWeek===i+1?'this-week':''}>{as.map(a=><div className="matrix-assignment" key={a.id}><button className={`matrix-item ${a.status}`} onClick={()=>focusTask(t.id)}><span>{a.commitment}</span><Pill status={a.status}/></button><div className="record-actions"><button onClick={()=>create('assignment',{task_id:a.task_id,cycle_id:a.cycle_id||'',commitment:a.commitment,review:a.review},a.id)}>编辑</button><button onClick={()=>unscheduleAssignment(a.id,i+1)}>移出本周</button></div></div>)}</td>})}</tr>}) : <tr><td colSpan={15}><Empty text="先创建本轮待办，这里会显示对应的年度目标与周任务" onClick={()=>create('task',{cycle_id:cycle.id})} button="新建本轮待办"/></td></tr>}</tbody></table></div>}</>}
        {page==='tasks'&&<><div className="page-heading"><div><div className="kicker">执行现场</div><h1>本轮待办</h1><p>这里与 12 周计划使用同一批待办，管理状态和每周推进。</p></div><button className="primary" onClick={()=>create('task',{cycle_id:cycle?.id||''})}><Plus size={16}/> 新建本轮待办</button></div><section className="panel"><H>全部本轮待办</H>{data.tasks.length ? data.tasks.map(t=><TaskCard key={t.id} task={t} data={data} create={create} deletePlanning={deletePlanning} mutate={mutate} setStatus={setStatus}/>) : <Empty text="还没有本轮待办" onClick={()=>create('task',{cycle_id:cycle?.id||''})} button="新建本轮待办"/>}</section></>}
        {page==='calendar'&&<><div className="page-heading"><div><div className="kicker">日程与实际</div><h1>{calendarTitle}</h1><p>周视图对照每日规划与实际时间；日、月、年视图查看任务安排。</p></div><div className="calendar-controls"><div className="segmented" aria-label="日程时间维度">{(['day','week','month','year'] as const).map(mode=><button key={mode} className={calendarMode===mode?'active':''} onClick={()=>setCalendarMode(mode)}>{({day:'日',week:'周',month:'月',year:'年'} as const)[mode]}</button>)}</div><div className="date-nav"><button className="icon-button" aria-label="上一时间段" onClick={()=>setDate(value=>shiftCalendarDate(value,calendarMode,-1))}><ChevronLeft size={18}/></button>{calendarMode==='day'&&<input type="date" value={date} onChange={e=>setDate(e.target.value)}/>}<button className="icon-button" aria-label="下一时间段" onClick={()=>setDate(value=>shiftCalendarDate(value,calendarMode,1))}><ChevronRight size={18}/></button><button className="outline" onClick={()=>setDate(localDate())}>今天</button></div></div></div>
          {calendarMode==='day'&&<><section className="panel day-task-panel"><H action={<button className="outline" onClick={()=>create('dayTask',{date})}><Plus size={15}/> 日任务</button>}>当日工作安排</H>{data.dayTasks.filter(t=>t.date===date).length?<div className="day-tasks">{data.dayTasks.filter(t=>t.date===date).map(t=><div className="day-task" key={t.id}><StatusSelect value={t.status} onChange={s=>setStatus('day_tasks',t.id,s)}/><strong>{dayTaskTimeLabel(t)&&<small className="task-clock">{dayTaskTimeLabel(t)} · </small>}{t.title}{t.assignment_id&&!assignmentsForDate(data,t.date).some(a=>a.id===t.assignment_id)&&<small className="mismatch">日期与周次不匹配</small>}</strong><Select value={t.assignment_id||''} onChange={e=>{const assignment=data.assignments.find(a=>a.id===e.target.value),task=data.tasks.find(x=>x.id===assignment?.task_id);mutate(()=>update('day_tasks',t.id,{assignment_id:assignment?.id||null,task_id:task?.id||null,project_id:task?.project_id||null}),'关联已更新')}}><option value="">临时 / 未关联周任务</option>{assignmentsForDate(data,t.date).map(a=><option key={a.id} value={a.id}>{a.commitment}</option>)}{t.assignment_id&&!assignmentsForDate(data,t.date).some(a=>a.id===t.assignment_id)&&<option value={t.assignment_id}>原关联周任务（当前周未安排）</option>}</Select><div className="record-actions"><button onClick={()=>editDayTask(t)}>编辑</button><button onClick={()=>deletePlanning('dayTask',t.id,t.title)}>删除</button></div></div>)}</div>:<Empty text="这一天还没有任务，历史日期也可以补录" onClick={()=>create('dayTask',{date})}/>}</section>
        <section className="panel day-legacy-plans"><H action={<button className="outline" onClick={()=>create('plan',{date,start:'09:00',end:'10:00'})}><Plus size={15}/> 单日计划</button>}>单日计划时段</H>{data.planBlocks.filter(plan=>plan.date===date).length ? data.planBlocks.filter(plan=>plan.date===date).sort((a,b)=>a.start_min-b.start_min).map(plan=><div className="day-plan-row" key={plan.id}><span>{minuteLabel(plan.start_min)}—{minuteLabel(plan.end_min)}</span><strong>{plan.title}</strong><div className="record-actions"><button onClick={()=>editPlan(plan)}>编辑</button><button onClick={()=>{if(confirm('删除这个计划时段？'))mutate(()=>removePlanBlock(plan.id),'计划已删除')}}>删除</button></div></div>) : <p className="calendar-overview-empty">暂无单日计划时段</p>}</section></>}{calendarMode!=='day'&&<CalendarOverview data={data} date={date} mode={calendarMode} onOpenDay={day=>{setDate(day);setCalendarMode('day')}} onOpenWeek={week=>{setDate(week);setCalendarMode('week')}} onOpenMonth={month=>{setDate(month);setCalendarMode('month')}} onCreateTemplate={(start,end)=>create('dailyPlan',{start,end})} onEditTemplate={editDailyPlan} onDeleteTemplate={plan=>{if(confirm(`删除每日规划“${plan.title}”？所有周将不再显示它。`))mutate(()=>remove('daily_plan_templates',plan.id),'每日规划已删除')}} onCreateEntry={(day,start,end)=>create('entry',{date:day,start,end})} onEditEntry={editEntry} onDeleteEntry={entry=>{if(confirm('删除这条实际记录？'))mutate(()=>remove('time_entries',entry.id),'记录已删除')}} onCreateAssignment={day=>create('assignment',{calendar_date:day})} onEditAssignment={item=>editNode('assignment',item.id)} onDeleteAssignment={item=>deletePlanning('assignment',item.id,item.commitment)} onAssignmentStatus={(item,status)=>setStatus('week_assignments',item.id,status)}/>}</>}
        {page==='reports'&&<><div className="page-heading"><div><div className="kicker">复盘统计</div><h1>时间花在了哪里</h1><p>百分比以已记录时间为分母，空白时段不参与计算。</p></div><div className="date-nav"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><div className="segmented">{(['day','week','month'] as const).map(m=><button key={m} className={reportMode===m?'active':''} onClick={()=>setReportMode(m)}>{m==='day'?'日':m==='week'?'周':'月'}</button>)}</div></div></div><Report data={data} date={date} mode={reportMode}/></>}
        {page==='history'&&<HistoryPage data={data} onToggleAnnual={toggleAnnual} onSetDayTaskStatus={(task,status)=>setStatus('day_tasks',task.id,status)} onEditDayTask={editDayTask} onDeleteDayTask={task=>deletePlanning('dayTask',task.id,task.title)} onSaveCycleReview={(cycle,review)=>{if(review!==cycle.review)mutate(()=>update('cycles',cycle.id,{review}),'周期复盘已保存');}}/>}
        {page==='settings'&&<><div className="page-heading"><div><div className="kicker">本地数据</div><h1>设置与备份</h1><p>分类、重复事项和数据库备份都在这台 Mac 上管理。</p></div></div><div className="settings-grid"><section className="panel"><H action={<button className="outline" onClick={()=>create('category')}><Plus size={15}/> 新分类</button>}>时间分类</H>{data.categories.map(c=><div className="settings-row" key={c.id}><span className="color-chip" style={{background:c.color}}/><input defaultValue={c.name} onBlur={e=>{if(e.target.value.trim()&&e.target.value!==c.name)mutate(()=>update('categories',c.id,{name:e.target.value.trim()}))}}/><input aria-label="分类颜色" type="color" value={c.color} onChange={e=>mutate(()=>update('categories',c.id,{color:e.target.value}))}/><button className="icon-button" title="删除分类" onClick={()=>{if(confirm('删除分类？已有时间记录使用的分类不能删除。'))mutate(()=>remove('categories',c.id))}}><Trash2 size={15}/></button></div>)}</section><section className="panel"><H action={<button className="outline" onClick={()=>create('recurrence',{kind:'day_task',frequency:'weekly',start_date:localDate()})}><Plus size={15}/> 新重复事项</button>}>重复事项</H>{data.recurrences.length?data.recurrences.map(r=><div className="settings-row" key={r.id}><RotateCcw size={16}/><div className="grow"><strong>{r.title}</strong><small>{r.frequency==='daily'?'每天':'每周'} · {r.kind==='plan'?'计划时段':'日任务'}</small></div><button className="text-button" onClick={()=>mutate(()=>update('recurrences',r.id,{active:r.active?0:1}),r.active?'已暂停':'已启用')}>{r.active?'暂停':'启用'}</button></div>):<Empty text="暂无重复事项"/>}</section><section className="panel backup-panel"><H>数据库备份</H><p>有变更的日期会自动生成一份备份，保留最近 30 份。手动备份可以保存到其他位置。</p><div className="backup-actions"><button className="primary" onClick={async()=>{const path=await save({defaultPath:`个人工作台-${localDate()}.db`,filters:[{name:'SQLite 数据库',extensions:['db']}]});if(path)try{await manualBackup(path);setMessage('备份已保存')}catch(e){setMessage(String(e))}}}><Save size={16}/> 手动备份</button><button className="outline" onClick={async()=>{const path=await open({multiple:false,filters:[{name:'SQLite 数据库',extensions:['db']}]});if(typeof path==='string'&&confirm('恢复后将替换当前全部数据，需要重新启动应用。继续吗？'))try{await stageRestore(path);setMessage('恢复文件已准备好。请完全退出并重新打开应用。')}catch(e){setMessage(String(e))}}}><ArchiveRestore size={16}/> 从文件恢复</button></div><button className="text-button" onClick={async()=>{try{setBackups(await listBackups())}catch(e){setMessage(String(e))}}}>查看自动备份</button>{backups.map(b=><div className="backup-file" key={b}><span>{b.split('/').pop()}</span><button onClick={async()=>{if(confirm('恢复该备份？需要重启应用。'))try{await stageRestore(b);setMessage('恢复文件已准备好。请完全退出并重新打开应用。')}catch(e){setMessage(String(e))}}}>恢复</button></div>)}</section></div></>}
      </div>}
    </main>
    {batch&&data&&<BatchCreate kind={batch.kind} defaults={batch.defaults} data={data} onClose={()=>setBatch(null)} onSave={async rows=>{const count=await batchCreate(batch.kind,rows);setBatch(null);try{await refresh(date);setMessage(`已新增 ${count} 项`);}catch(error){setMessage(`已新增 ${count} 项，但刷新失败，请重新打开应用：${String(error)}`);}}}/>}
    {form&&data&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setForm(null)}}><div className="modal" role="dialog" aria-modal="true"><div className="modal-head"><div><small>{form.editingId?'编辑记录':'添加记录'}</small><h2>{formTitle(form.kind)}</h2></div><button className="icon-button" onClick={()=>setForm(null)}>✕</button></div><div className="form-grid">{formFields.map(f=><label key={f.name}><span>{f.label}</span>{f.type==='select'?<Select aria-label={f.label} value={form.values[f.name]||''} onChange={e=>setField(f.name,e.target.value)}><option value="">请选择</option>{f.options?.map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select>:f.type==='textarea'?<textarea rows={3} value={form.values[f.name]||''} onChange={e=>setField(f.name,e.target.value)}/>:<input type={f.type||'text'} value={form.values[f.name]||''} onChange={e=>setField(f.name,e.target.value)} placeholder={f.placeholder||''}/>}</label>)}</div>{form.kind==='assignment'&&form.values.calendar_date&&<p className="muted calendar-placement-hint">{(()=>{const placement=calendarTaskPlacement(data,form.values.task_id,form.values.calendar_date);return placement?`保存后安排到 ${placement.cycle.title} · 第 ${placement.week} 周（${weekStart(placement.cycle,placement.week)} — ${addDays(weekStart(placement.cycle,placement.week),6)}）。`:'请选择所属周期覆盖查看周的本轮待办；没有合适待办时，先到 12 周计划中创建。';})()}</p>}<p className="form-feedback" role="status">{message}</p><div className="modal-footer"><button className="outline" onClick={()=>setForm(null)}>取消</button><button className="primary" disabled={busy} onClick={submitForm}>{busy?'保存中…':'保存'}</button></div></div></div>}
  </div>;
}

type Field={name:string;label:string;type?:string;placeholder?:string;options?:[string,string][]};
function fieldsFor(kind:FormKind,data:Data|null,_cycleId?:string,date?:string):Field[] {
  if(!data)return [];
  const dirs=data.directions.map(x=>[x.id,x.title] as [string,string]),annual=data.annualGoals.map(x=>[x.id,`${x.year} · ${data.directions.find(d=>d.id===x.direction_id)?.title||'未归属方向'} · ${x.title}`] as [string,string]),cycles=data.cycles.map(x=>[x.id,x.title] as [string,string]),allTasks=data.tasks.map(x=>[x.id,`${data.cycles.find(c=>c.id===x.cycle_id)?.title||'未归属周期'} · ${x.title}`] as [string,string]),assignments=assignmentsForDate(data,date||localDate()).map(x=>[x.id,`${data.tasks.find(t=>t.id===x.task_id)?.title||'未归属待办'} · ${x.commitment}`] as [string,string]),dayTasks=data.dayTasks.filter(x=>x.date===date).map(x=>[x.id,x.title] as [string,string]);
  const title:Field={name:'title',label:'标题',placeholder:'写下具体要完成的事'};
  if(kind==='cycle')return [title,{name:'start_date',label:'第一周开始日期',type:'date'}];
  if(kind==='direction')return [title];
  if(kind==='annual')return [{name:'direction_id',label:'年度方向',type:'select',options:dirs},title,{name:'year',label:'年份',type:'number'}];
  if(kind==='task')return [title,{name:'cycle_id',label:'12 周周期',type:'select',options:cycles},{name:'annual_goal_id',label:'年度目标',type:'select',options:annual},{name:'due_date',label:'截止日期（可选）',type:'date'}];
  if(kind==='assignment')return [{name:'task_id',label:'本轮待办',type:'select',options:allTasks},{name:'commitment',label:'周任务内容',type:'textarea'},{name:'review',label:'复盘（可选，多周共用）',type:'textarea'}];
  if(kind==='dayTask')return [{name:'date',label:'日期',type:'date'},{name:'title',label:'具体内容',placeholder:'例如：面试'},{name:'assignment_id',label:'关联周任务（可选）',type:'select',options:assignments},{name:'start',label:'具体时间 · 开始（可选）',type:'time'},{name:'end',label:'具体时间 · 结束（可选，早于开始则为次日）',type:'time'},{name:'category_id',label:'时间分类（填写具体时间时必选）',type:'select',options:data.categories.map(x=>[x.id,x.name])}];
  if(kind==='plan')return [{name:'date',label:'日期',type:'date'},{name:'start',label:'开始时间',type:'time'},{name:'end',label:'结束时间',type:'time'},title,{name:'day_task_id',label:'关联日任务（可选）',type:'select',options:dayTasks}];
  if(kind==='dailyPlan')return [{name:'start',label:'开始时间',type:'time'},{name:'end',label:'结束时间',type:'time'},title];
  if(kind==='entry')return [{name:'date',label:'开始日期',type:'date'},{name:'start',label:'开始时间',type:'time'},{name:'end',label:'结束时间（早于开始则为次日）',type:'time'},{name:'title',label:'具体内容（可选）',placeholder:'记录这段时间做了什么'}, {name:'category_id',label:'时间分类',type:'select',options:data.categories.map(x=>[x.id,x.name])},{name:'day_task_id',label:'关联日任务（可选）',type:'select',options:dayTasks}];
  if(kind==='category')return [{name:'name',label:'分类名称'},{name:'color',label:'颜色',type:'color'}];
  if(kind==='recurrence')return [{name:'kind',label:'生成类型',type:'select',options:[['day_task','日任务'],['plan','计划时段']]},{name:'frequency',label:'重复频率',type:'select',options:[['daily','每天'],['weekly','每周']]},title,{name:'start_date',label:'开始日期',type:'date'},{name:'end_date',label:'结束日期（可选）',type:'date'},{name:'weekdays',label:'每周星期（0=周日，1=周一；多个用逗号分隔）',placeholder:'例如 1,3,5'},{name:'start',label:'计划开始时间（计划时段填写）',type:'time'},{name:'end',label:'计划结束时间（计划时段填写）',type:'time'},{name:'task_id',label:'关联本轮待办（可选）',type:'select',options:allTasks}];
  return [];
}
function formTitle(kind:FormKind) {return ({cycle:'12 周周期',direction:'年度方向',annual:'年度目标',task:'本轮待办',assignment:'周任务',dayTask:'日任务',plan:'计划时段',dailyPlan:'每日规划',entry:'实际时间记录',category:'时间分类',recurrence:'重复事项'} as Record<FormKind,string>)[kind]}

function AnnualCards({data,year,onYear,cycleId,create,edit,deleteAnnual,toggleAnnual,focusTask}:{data:Data;year:number;onYear:(year:number)=>void;cycleId:string;create:CreateFn;edit:(kind:BatchKind,id:string)=>void;deleteAnnual:(id:string,title:string)=>void;toggleAnnual:(row:Data['annualGoals'][number])=>void;focusTask:(id:string)=>void}) {
  const groups=[...data.directions.map(item=>({id:item.id,title:item.title})),{id:null,title:'未归属年度方向'}];
  const goals=data.annualGoals.filter(item=>item.year===year);
  return <section className="panel annual-section"><H action={<div className="heading-actions"><Select aria-label="年度目标年份" value={String(year)} onChange={event=>onYear(Number(event.target.value))}>{[...new Set([year,new Date().getFullYear(),...data.annualGoals.map(item=>item.year)])].sort((a,b)=>b-a).map(value=><option key={value} value={value}>{value} 年</option>)}</Select><button className="outline" onClick={()=>create('annual',{year:String(year)})}>＋ 年度目标</button></div>}>年度目标卡片</H>
  {groups.map(group=>{const items=goals.filter(item=>group.id?item.direction_id===group.id:!item.direction_id||!data.directions.some(d=>d.id===item.direction_id));return items.length?<div className="annual-direction-group" key={group.id||'orphan'}><h3>{group.title}</h3><div className="annual-grid">{items.map(annual=>{const linked=data.tasks.filter(t=>t.annual_goal_id===annual.id);return <div className="annual-card" key={annual.id}><div className="annual-meta"><span>{group.title}</span><strong>{annual.year}</strong></div><h3>{annual.title}</h3><button className={`history-complete ${annual.completed===1?'done':''}`} onClick={()=>toggleAnnual(annual)}>{annual.completed===1?'已完成':'未完成'}</button><Progress items={annualGoalTasks(data,annual)}/><div className="annual-linked"><span>关联的本轮待办 · {linked.length}</span>{linked.map(task=><button key={task.id} onClick={()=>focusTask(task.id)}>{task.title}<ChevronRight size={18}/></button>)}</div><div className="record-actions"><button onClick={()=>edit('annual',annual.id)}>编辑</button><button onClick={()=>create('task',{cycle_id:cycleId,annual_goal_id:annual.id})}>＋ 本轮待办</button><button onClick={()=>deleteAnnual(annual.id,annual.title)}>删除年度目标</button></div></div>})}</div></div>:null;})}
  {!goals.length&&<Empty text="这一年还没有年度目标" onClick={()=>create('annual',{year:String(year)})}/>}
  </section>;
}

function WeekTaskPool({data,cycleId,create,deletePlanning,schedule,unschedule,setStatus}:{data:Data;cycleId:string|null;create:CreateFn;deletePlanning:DeleteFn;schedule:(id:string,week:number)=>void;unschedule:(id:string,week:number)=>void;setStatus:(table:string,id:string,status:Status)=>void}) {
  const items=data.assignments.filter(item=>item.cycle_id===cycleId);
  return <section className="panel week-task-pool"><H action={<button className="outline" onClick={()=>create('assignment',{cycle_id:cycleId||''})}><Plus size={15}/> 周任务</button>}>周任务待办池</H>
    {items.length ? <div className="week-pool-list">{items.map(item=>{const weeks=data.assignmentWeeks.filter(row=>row.assignment_id===item.id).map(row=>row.week_no).sort((a,b)=>a-b);return <div className="week-pool-item" key={item.id} id={`week-pool-${item.id}`}>
      <div className="week-pool-main"><strong>{item.commitment}</strong><small>{data.tasks.find(task=>task.id===item.task_id)?.title||'本轮待办已删除'} · {weeks.length ? `已安排 ${weeks.length} 周` : '待安排'}</small></div>
      <StatusSelect value={item.status} onChange={status=>setStatus('week_assignments',item.id,status)}/>
      <div className="week-pool-weeks">{weeks.map(week=><button key={week} className="week-pool-chip" title={`移出第 ${week} 周，保留日任务关联`} onClick={()=>unschedule(item.id,week)}>第 {week} 周 ×</button>)}<Select aria-label={`安排“${item.commitment}”到周次`} disabled={!item.cycle_id} value="" onChange={event=>{if(event.target.value)schedule(item.id,Number(event.target.value))}}><option value="">＋ 安排到周</option>{Array.from({length:12},(_,index)=>index+1).filter(week=>!weeks.includes(week)).map(week=><option key={week} value={week}>第 {week} 周</option>)}</Select></div>
      <div className="record-actions"><button onClick={()=>create('assignment',{task_id:item.task_id,cycle_id:item.cycle_id||'',commitment:item.commitment,review:item.review},item.id)}>编辑</button><button onClick={()=>deletePlanning('assignment',item.id,item.commitment)}>删除</button></div>
    </div>})}</div> : <Empty text="待办池还没有周任务" onClick={()=>create('assignment',{cycle_id:cycleId||''})} button="新建周任务"/>}
  </section>;
}

function TaskCard({task,data,create,deletePlanning,mutate,setStatus}:{task:Task;data:Data;create:CreateFn;deletePlanning:DeleteFn;mutate:(fn:()=>Promise<unknown>,s?:string)=>Promise<void>;setStatus:(t:string,id:string,s:Status)=>void}) {
  const as=data.assignments.filter(a=>a.task_id===task.id).sort((a,b)=>a.created_at.localeCompare(b.created_at)), allDone=as.length>0&&as.every(a=>a.status==='done');
  return <div className="task-card" id={`task-${task.id}`}><div className="task-card-head"><div><strong>{task.title}</strong><small>{data.annualGoals.find(g=>g.id===task.annual_goal_id)?.title||'未关联年度目标'}{task.due_date&&` · 截止 ${task.due_date}`}</small></div><div className="card-controls"><StatusSelect value={task.status} onChange={s=>setStatus('tasks',task.id,s)}/><div className="record-actions"><button onClick={()=>create('task',{title:task.title,cycle_id:task.cycle_id||'',annual_goal_id:task.annual_goal_id||'',due_date:task.due_date||''},task.id)}>编辑</button><button onClick={()=>deletePlanning('task',task.id,task.title)}>删除</button></div></div></div><div className="assignment-list">{as.map(a=>{const ds=data.dayTasks.filter(d=>d.assignment_id===a.id),suggest=ds.length>0&&ds.every(d=>d.status==='done')&&a.status!=='done';return <div className="assignment-row" key={a.id}><span className="week-label">{data.assignmentWeeks.filter(w=>w.assignment_id===a.id).map(w=>`第 ${w.week_no} 周`).join('、')||'待办池'}</span><div className="assignment-body"><strong>{a.commitment}</strong><span>{ds.length} 个日任务 · {ds.filter(d=>d.status==='done').length} 个完成</span><input placeholder="周任务复盘（多周共用）" defaultValue={a.review} onBlur={e=>{if(e.target.value!==a.review)mutate(()=>update('week_assignments',a.id,{review:e.target.value}),'复盘已保存')}}/>{suggest&&<button className="suggestion" onClick={()=>setStatus('week_assignments',a.id,'done')}>日任务均已完成，确认本周完成</button>}</div><div className="card-controls"><StatusSelect value={a.status} onChange={s=>setStatus('week_assignments',a.id,s)}/><div className="record-actions"><button onClick={()=>create('assignment',{task_id:a.task_id,cycle_id:a.cycle_id||'',commitment:a.commitment,review:a.review},a.id)}>编辑</button><button onClick={()=>deletePlanning('assignment',a.id,a.commitment)}>删除</button></div></div></div>})}</div><div className="task-actions"><button disabled={!task.cycle_id} title={task.cycle_id?'':'请先编辑待办并选择 12 周周期与年度目标'} onClick={()=>create('assignment',{task_id:task.id,cycle_id:task.cycle_id||''})}>＋ 周任务</button><button onClick={()=>create('dayTask',{date:localDate(),title:task.title,assignment_id:as.length===1&&assignmentsForDate(data,localDate()).some(a=>a.id===as[0].id)?as[0].id:''})}>＋ 添加日任务</button>{allDone&&task.status!=='done'&&<button className="suggestion" onClick={()=>setStatus('tasks',task.id,'done')}>各周已完成，确认本轮待办完成</button>}</div></div>;
}
function Report({data,date,mode}:{data:Data;date:string;mode:'day'|'week'|'month'}) {
  const weekday=(new Date(`${date}T12:00:00`).getDay()+6)%7;
  const from=mode==='day'?date:mode==='week'?addDays(date,-weekday):`${date.slice(0,7)}-01`;
  const to=mode==='day'?addDays(date,1):mode==='week'?addDays(from,7):localDate(new Date(Number(date.slice(0,4)),Number(date.slice(5,7)),1));
  const totals=categoryTotals(data.timeEntries,data.categories,from,to);
  const plans=data.planBlocks.filter(p=>p.date>=from&&p.date<to), entries=data.timeEntries.filter(e=>new Date(e.end_at)>new Date(`${from}T00:00:00`)&&new Date(e.start_at)<new Date(`${to}T00:00:00`));
  return <><div className="report-summary"><div className="panel"><span>统计范围</span><strong>{from} — {addDays(to,-1)}</strong></div><div className="panel"><span>已记录时间</span><strong>{formatHours(totals.total)}</strong></div><div className="panel"><span>计划时段</span><strong>{formatHours(plans.reduce((n,p)=>n+p.end_min-p.start_min,0))}</strong></div></div><div className="report-grid"><section className="panel"><H>分类占比</H>{totals.rows.length?totals.rows.map(x=><div className="category-row" key={x.category.id}><span className="color-chip" style={{background:x.category.color}}/><strong>{x.category.name}</strong><span>{formatHours(x.minutes)}</span><b>{x.percent.toFixed(1)}%</b><div className="category-bar"><i style={{width:`${x.percent}%`,background:x.category.color}}/></div></div>):<Empty text="这个时间范围还没有实际记录"/>}</section><section className="panel"><H>计划与实际</H><div className="report-compare"><div><strong>计划</strong>{plans.length?plans.slice(0,25).map(p=><p key={p.id}><span>{p.date.slice(5)} {minuteLabel(p.start_min)}</span>{p.title}</p>):<span className="muted">暂无计划时段</span>}</div><div><strong>实际</strong>{entries.length?entries.slice(0,25).map(e=><p key={e.id}><span>{localDate(new Date(e.start_at)).slice(5)} {new Date(e.start_at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</span>{e.title||data.categories.find(c=>c.id===e.category_id)?.name||'实际记录'}</p>):<span className="muted">暂无实际记录</span>}</div></div></section></div></>;
}
