import { describe,it,expect } from 'vitest';
import { prepareRow,RowError } from './batch';
import { EMPTY,type Data,type TimeEntry } from './model';
const data:Data={...EMPTY,directions:[{id:'dir',title:'方向',created_at:''}],annualGoals:[{id:'a',direction_id:'dir',title:'目标',year:2026,completed:0,created_at:''}],cycles:[{id:'c',title:'周期',start_date:'2026-10-01',review:'',created_at:''}],tasks:[{id:'t',title:'待办',cycle_id:'c',annual_goal_id:'a',cycle_goal_id:null,project_id:null,status:'todo',due_date:null,created_at:''}],assignments:[{id:'w',task_id:'t',cycle_id:'c',commitment:'周任务',status:'todo',review:'',created_at:''}],assignmentWeeks:[{assignment_id:'w',week_no:1}],categories:[{id:'cat',kind:'goal',active:1,annual_goal_id:'a',goal_year:2026,name:'工作',color:'#fff',created_at:''}]};
describe('批量新增校验',()=>{
 it('分别保存同名方向，使用不同ID',()=>{const a=prepareRow('direction',{title:'同名'},data),b=prepareRow('direction',{title:'同名'},data);expect(a.values.id).not.toBe(b.values.id);});
 it('校验必填父级及周次，并允许周任务先不安排',()=>{expect(()=>prepareRow('annual',{title:'目标',year:'2026'},data)).toThrow(RowError);expect(prepareRow('assignment',{commitment:'任务',task_id:'t'},data).weeks).toEqual([]);expect(prepareRow('assignment',{commitment:'任务',task_id:'t',weeks:'1,3'},data).weeks).toEqual([1,3]);expect(()=>prepareRow('assignment',{commitment:'任务',task_id:'t',weeks:'1,1'},data)).toThrow('不重复');});
 it('日任务只关联日期所在周任务',()=>{expect(()=>prepareRow('dayTask',{date:'2026-10-08',title:'任务',assignment_id:'w'},data)).toThrow('所在周');expect(prepareRow('dayTask',{date:'2026-10-01',title:'任务',assignment_id:'w'},data).values.task_id).toBe('t');});
 it('具体时间必须完整，跨午夜时段生成正确结束日期',()=>{expect(()=>prepareRow('dayTask',{date:'2026-10-01',title:'任务',start:'23:00'},data)).toThrow('结束');const row=prepareRow('dayTask',{date:'2026-10-01',title:'任务',start:'23:00',end:'01:00',category_id:'cat'},data);expect(new Date(String(row.values.scheduled_end_at)).getTime()-new Date(String(row.values.scheduled_start_at)).getTime()).toBe(7200000);});
 it('检查本批已准备时段之间的冲突',()=>{const first=prepareRow('dayTask',{date:'2026-10-01',title:'任务',start:'23:00',end:'01:00',category_id:'cat'},data);const existing=[{id:'e',start_at:first.values.scheduled_start_at,end_at:first.values.scheduled_end_at}] as TimeEntry[];expect(()=>prepareRow('dayTask',{date:'2026-10-02',title:'冲突',start:'00:30',end:'02:00',category_id:'cat'},data,existing)).toThrow('重叠');});
 it('无具体时间的日任务不生成时间字段，拒绝不存在的日期',()=>{const row=prepareRow('dayTask',{date:'2026-10-01',title:'任务'},data);expect(row.values.scheduled_start_at).toBeNull();expect(()=>prepareRow('dayTask',{date:'2026-02-30',title:'任务'},data)).toThrow('日期无效');});
});
