import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import Select from './Select';
import PriorityBadge from './PriorityBadge';
import { assignmentsForDate, dayTaskTaskId, dayTaskTimeLabel, localDate, PRIORITY, STATUS, type Data, type Status } from './model';
import { statusCounts } from './taskQueries';
type Props={data:Data;onCreate:()=>void;onEdit:(id:string)=>void;onDelete:(id:string,title:string)=>void;onStatus:(id:string,status:Status)=>void};
export default function DayTaskPool({data,onCreate,onEdit,onDelete,onStatus}:Props){
 const [query,setQuery]=useState(''),[status,setStatus]=useState(''),[priority,setPriority]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[assignment,setAssignment]=useState(''),[project,setProject]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<string|null>(null);
 const [narrow,setNarrow]=useState(()=>window.matchMedia('(max-width:1150px)').matches);
 useEffect(()=>{const media=window.matchMedia('(max-width:1150px)'),change=()=>setNarrow(media.matches);media.addEventListener('change',change);return()=>media.removeEventListener('change',change);},[]);
 useEffect(()=>{setPage(1);setSelected(null);},[query,status,priority,from,to,assignment,project]);
 useEffect(()=>{if(!selected)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!e.defaultPrevented)setSelected(null);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[selected]);
 const items=data.dayTasks.filter(d=>d.title.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())&&(!status||d.status===status)&&(!priority||(d.priority||'__none')===priority)&&(!from||d.date>=from)&&(!to||d.date<=to)&&(!assignment||(d.assignment_id||'__none')===assignment)&&(!project||d.long_project_id===project)).sort((a,b)=>b.date.localeCompare(a.date)||b.created_at.localeCompare(a.created_at));
 const pages=Math.max(1,Math.ceil(items.length/50)),current=Math.min(page,pages),counts=statusCounts(items),detail=data.dayTasks.find(d=>d.id===selected),parent=data.assignments.find(w=>w.id===detail?.assignment_id);
 const state=(id:string,value:Status)=><Select className={`status ${value}`} aria-label="日任务状态" value={value} onChange={e=>onStatus(id,e.target.value as Status)}>{Object.entries(STATUS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select>;
 const filter=(label:string,value:string,set:(value:string)=>void,options:[string,string][])=><label><span>{label}</span><Select aria-label={`日任务${label}筛选`} value={value} onChange={e=>set(e.target.value)}><option value="">全部{label}</option>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select></label>;
 const panel=detail?<><button className="task-detail-scrim" aria-label="关闭日任务详情" onClick={()=>setSelected(null)}/><aside className="task-detail" role={narrow?'dialog':undefined} aria-modal={narrow?true:undefined} aria-label="日任务详情"><div className="section-head"><h3>{detail.title}</h3><button className="icon-button" aria-label="关闭日任务详情" onClick={()=>setSelected(null)}>×</button></div>{state(detail.id,detail.status)}<dl><dt>日期</dt><dd>{detail.date}</dd><dt>具体时间</dt><dd>{dayTaskTimeLabel(detail)||'未设置'}</dd><dt>紧急程度</dt><dd>{detail.priority?`${detail.priority} · ${PRIORITY[detail.priority]}`:'未设置'}</dd><dt>关联周任务</dt><dd>{parent?.commitment||'未关联'}</dd><dt>本轮待办</dt><dd>{data.tasks.find(t=>t.id===dayTaskTaskId(data,detail))?.title||'未关联'}</dd><dt>项目</dt><dd>{data.longProjects.find(p=>p.id===detail.long_project_id)?.title||'未关联'}</dd></dl>{detail.assignment_id&&!assignmentsForDate(data,detail.date).some(w=>w.id===detail.assignment_id)&&<p className="mismatch">日期与周次不匹配；已有的关联仍保留。</p>}<div className="record-actions"><button onClick={()=>onEdit(detail.id)}>编辑</button><button onClick={()=>onDelete(detail.id,detail.title)}>删除</button></div></aside></>:null;
 return <section className="panel task-manager"><div className="section-head"><h2>日任务池</h2><button className="outline" onClick={onCreate}>＋ 日任务</button></div><p className="muted">查看全部已保存日任务，可按日期查找历史任务和未完成任务。</p><div className="task-manager-filters"><label className="task-search"><span>查找内容</span><input aria-label="搜索日任务池" value={query} onChange={e=>setQuery(e.target.value)} placeholder="输入任务内容…"/></label>{filter('状态',status,setStatus,Object.entries(STATUS))}{filter('紧急程度',priority,setPriority,[...Object.entries(PRIORITY).map(([v,l])=>[v,`${v} · ${l}`] as [string,string]),['__none','未设置']])}<label><span>开始日期</span><input aria-label="日任务开始日期" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label><span>结束日期</span><input aria-label="日任务结束日期" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>{filter('周任务',assignment,setAssignment,[['__none','未关联周任务'],...data.assignments.map(w=>[w.id,`${data.tasks.find(t=>t.id===w.task_id)?.title||'未归属待办'} · ${w.commitment}`] as [string,string])])}{filter('项目',project,setProject,data.longProjects.map(p=>[p.id,p.title]))}<button className="text-button" onClick={()=>{setQuery('');setStatus('');setPriority('');setFrom('');setTo('');setAssignment('');setProject('');}}>清除筛选</button><button className="text-button" onClick={()=>{setFrom(localDate());setTo(localDate());}}>今天</button></div><div className="task-manager-summary"><strong>当前筛选结果 · {items.length} 项</strong>{Object.entries(STATUS).map(([v,l])=><span className={`pill ${v}`} key={v}>{l} {counts[v]}</span>)}</div><div className={`task-manager-body ${detail?'with-detail':''}`}><div className="task-manager-results">{items.slice((current-1)*50,current*50).map(d=><div className={`compact-task-row ${selected===d.id?'selected':''}`} key={d.id}><button className="compact-task-main" aria-label={`查看日任务${d.title}详情`} onClick={()=>setSelected(d.id)}><strong>{d.title}</strong><small>{d.date} {dayTaskTimeLabel(d)} · {data.assignments.find(w=>w.id===d.assignment_id)?.commitment||'未关联周任务'}</small></button><PriorityBadge value={d.priority}/><div className="compact-task-status">{state(d.id,d.status)}</div></div>)}{!items.length&&<p className="empty">{data.dayTasks.length?'没有匹配的日任务，请调整或清除筛选。':'还没有日任务，点击“＋ 日任务”开始添加。'}</p>}<div className="task-pagination"><span>共 {items.length} 项 · 每页 50 条</span><button className="outline" disabled={current<=1} onClick={()=>setPage(current-1)}>上一页</button><span>{current} / {pages}</span><button className="outline" disabled={current>=pages} onClick={()=>setPage(current+1)}>下一页</button></div></div>{narrow&&panel?createPortal(panel,document.body):panel}</div></section>;
}
