import { useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { ChevronRight, Plus } from 'lucide-react';
import Select from './Select';
import PriorityBadge from './PriorityBadge';
import { addDays, dayTaskTimeLabel, localDate, STATUS, type Cycle, type Data, type Status } from './model';
import { homeSummary, overdueTasks, type OverdueItem } from './homeQueries';
import type { Filters } from './taskQueries';
type Kind='dayTask'|'assignment'|'task';
type Props={data:Data;cycle?:Cycle;onCreate:(kind:Kind|'cycle',values?:Record<string,string>)=>void;onEdit:(kind:Kind,id:string)=>void;onDelete:(kind:Kind,id:string,title:string)=>void;onStatus:(table:string,id:string,status:Status)=>void;onCalendar:()=>void;onCycles:()=>void;onPool:(kind:'task'|'assignment',filters:Partial<Filters>)=>void};
export default function HomeOverview({data,cycle,onCreate,onEdit,onDelete,onStatus,onCalendar,onCycles,onPool}:Props){
 const today=localDate(),summary=homeSummary(data,cycle,today),overdue=overdueTasks(data,today);
 const [tab,setTab]=useState<Kind>('dayTask'),[page,setPage]=useState(1),[menu,setMenu]=useState<{item:{kind:Kind;id:string;title:string};left:number;top:number}|null>(null);
 useEffect(()=>{if(!menu)return;document.querySelector<HTMLButtonElement>('.home-action-menu button')?.focus();const close=(e:Event)=>{if(!(e.target instanceof Element)||!e.target.closest('.home-action-menu,.home-more'))setMenu(null);},key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(null);document.getElementById(`home-more-${menu.item.kind}-${menu.item.id}`)?.focus();}};window.addEventListener('pointerdown',close);window.addEventListener('keydown',key);window.addEventListener('resize',close);window.addEventListener('scroll',close,true);return()=>{window.removeEventListener('pointerdown',close);window.removeEventListener('keydown',key);window.removeEventListener('resize',close);window.removeEventListener('scroll',close,true);};},[menu]);
 const status=(kind:Kind,id:string,value:Status)=><Select aria-label="任务状态" className={`status home-status ${value}`} value={value} onChange={e=>onStatus(({dayTask:'day_tasks',assignment:'week_assignments',task:'tasks'})[kind],id,e.target.value as Status)}>{Object.entries(STATUS).map(([key,label])=><option key={key} value={key}>{label}</option>)}</Select>;
 const more=(kind:Kind,id:string,title:string)=><button id={`home-more-${kind}-${id}`} className="home-more" aria-label={`管理${title}`} aria-haspopup="menu" aria-expanded={menu?.item.id===id&&menu.item.kind===kind} onClick={e=>{const rect=e.currentTarget.getBoundingClientRect();setMenu(menu?.item.id===id&&menu.item.kind===kind?null:{item:{kind,id,title},left:Math.max(8,Math.min(rect.right-144,window.innerWidth-152)),top:Math.max(8,Math.min(rect.bottom+4,window.innerHeight-104))});}}>⋯</button>;
 const dayRow=(item:Data['dayTasks'][number])=><div className="home-task-row" key={item.id}>{status('dayTask',item.id,item.status)}<button className="home-task-content" onClick={()=>onEdit('dayTask',item.id)}><strong>{item.title}</strong><small>{dayTaskTimeLabel(item)||'时间未设置'}</small></button><PriorityBadge value={item.priority}/>{more('dayTask',item.id,item.title)}</div>;
 const weekRow=(item:Data['assignments'][number])=><div className="home-task-row" key={item.id}>{status('assignment',item.id,item.status)}<button className="home-task-content" onClick={()=>onEdit('assignment',item.id)}><strong>{item.commitment}</strong><small>{data.tasks.find(t=>t.id===item.task_id)?.title||'未关联本轮待办'}</small></button><PriorityBadge value={item.priority}/>{more('assignment',item.id,item.commitment)}</div>;
 const activeDays=summary.today.filter(d=>d.status!=='done'),doneDays=summary.today.filter(d=>d.status==='done'),activeWeeks=summary.thisWeek.filter(w=>w.status!=='done'),doneWeeks=summary.thisWeek.filter(w=>w.status==='done');
 const filtered=overdue.filter(o=>o.kind===tab),pages=Math.max(1,Math.ceil(filtered.length/20)),currentPage=Math.min(page,pages),rows=filtered.slice((currentPage-1)*20,currentPage*20);
 const overdueRow=(item:OverdueItem)=><div className="home-task-row home-overdue-row" key={item.id}>{status(item.kind,item.id,item.status)}<button className="home-task-content" onClick={()=>onEdit(item.kind,item.id)}><strong>{item.title}</strong><small>{item.date} · 逾期 {item.days} 天{item.kind!=='dayTask'&&` · ${data.cycles.find(c=>c.id===item.cycleId)?.title||'未归属周期'}`}</small></button><PriorityBadge value={item.priority}/>{item.kind==='dayTask'&&<button className="home-reschedule" onClick={()=>onEdit('dayTask',item.id)}>重新安排</button>}{more(item.kind,item.id,item.title)}</div>;
 return <div className="home-overview"><div className="page-heading"><div><div className="kicker">{new Date(`${today}T12:00:00`).toLocaleDateString('zh-CN',{weekday:'long',month:'long',day:'numeric'})}</div><h1>今天，从最重要的事开始。</h1><p>处理今天与本周的任务，也照顾尚未完成的计划。</p></div><button className="outline" onClick={onCalendar}>打开日程 <ChevronRight size={16}/></button></div>
 <div className="home-execution"><section className="panel home-work-panel" aria-labelledby="home-today-title"><div className="section-head"><div><h2 id="home-today-title">今日任务 <span className="home-count">{doneDays.length} / {summary.today.length}</span></h2><p className="home-caption">{today} · 已完成 / 总数</p></div><button className="outline" onClick={()=>onCreate('dayTask',{date:today})}><Plus size={15}/>日任务</button></div><div className="home-task-scroll">{activeDays.map(dayRow)}{!summary.today.length&&<p className="home-empty">今天还没有任务，点击上方“＋日任务”开始安排。</p>}{summary.today.length>0&&!activeDays.length&&<p className="home-empty">今日任务已全部完成。</p>}</div>{doneDays.length>0&&<details className="home-done"><summary>已完成 {doneDays.length} 项</summary><div className="home-task-scroll">{doneDays.map(dayRow)}</div></details>}</section>
 <section className="panel home-work-panel" aria-labelledby="home-week-title"><div className="section-head"><div><h2 id="home-week-title">本周任务 <span className="home-count">{doneWeeks.length} / {summary.thisWeek.length}</span></h2><p className="home-caption">{cycle&&summary.phase==='active'?`${cycle.title} · 第 ${summary.week} 周`:'当前所选周期没有本周安排'}</p></div><button className="outline" onClick={()=>onCreate('assignment',{calendar_date:today,cycle_id:cycle?.id||''})}><Plus size={15}/>周任务</button></div><div className="home-task-scroll">{activeWeeks.map(weekRow)}{!summary.thisWeek.length&&<p className="home-empty">本周还没有周任务，可新增或到周任务池安排。</p>}{summary.thisWeek.length>0&&!activeWeeks.length&&<p className="home-empty">本周任务已全部完成。</p>}</div>{doneWeeks.length>0&&<details className="home-done"><summary>已完成 {doneWeeks.length} 项</summary><div className="home-task-scroll">{doneWeeks.map(weekRow)}</div></details>}</section></div>
 <section className="panel home-overdue" aria-labelledby="home-overdue-title"><div className="section-head"><div><h2 id="home-overdue-title">逾期任务</h2><p className="home-caption">保留所有非已完成任务，可更新状态或重新安排。</p></div><span className="home-count">共 {overdue.length} 项</span></div><div className="home-overdue-tabs" role="tablist" aria-label="逾期任务类型">{(['dayTask','assignment','task'] as const).map(kind=><button role="tab" id={`overdue-tab-${kind}`} aria-controls="home-overdue-results" aria-selected={tab===kind} className={tab===kind?'active':''} key={kind} onClick={()=>{setTab(kind);setPage(1);}}>{({dayTask:'日任务',assignment:'周任务',task:'本轮待办'})[kind]} <span>{overdue.filter(o=>o.kind===kind).length}</span></button>)}</div><div id="home-overdue-results" role="tabpanel" aria-labelledby={`overdue-tab-${tab}`}>{!rows.length?<p className="home-empty">没有逾期的{({dayTask:'日任务',assignment:'周任务',task:'本轮待办'})[tab]}。</p>:tab==='dayTask'?<>{rows.some(o=>o.date===addDays(today,-1))&&<div className="home-overdue-group"><h3>昨日遗留</h3>{rows.filter(o=>o.date===addDays(today,-1)).map(overdueRow)}</div>}{rows.some(o=>o.date<addDays(today,-1))&&<div className="home-overdue-group"><h3>更早未完成</h3>{rows.filter(o=>o.date<addDays(today,-1)).map(overdueRow)}</div>}</>:rows.map(overdueRow)}{filtered.length>0&&<div className="task-pagination"><span>共 {filtered.length} 项 · 每页 20 条</span><button className="outline" disabled={currentPage<=1} onClick={()=>setPage(currentPage-1)}>上一页</button><span>{currentPage} / {pages}</span><button className="outline" disabled={currentPage>=pages} onClick={()=>setPage(currentPage+1)}>下一页</button></div>}</div></section>
 <section className="panel home-cycle" aria-labelledby="home-cycle-title"><div className="section-head"><div><p className="home-caption">当前 12 周周期</p><h2 id="home-cycle-title">{cycle?.title||'未选择周期'}</h2></div><button className="text-button" onClick={onCycles}>查看 12 周计划 <ChevronRight size={16}/></button></div>{cycle?<><div className="home-cycle-timeline"><span>{cycle.start_date} — {addDays(cycle.start_date,83)}</span><strong>{summary.phase==='future'?'尚未开始':summary.phase==='ended'?'已结束':`第 ${summary.week} / 12 周 · 剩余 ${summary.remaining} 天`}</strong><label>周期时间进度 <progress max={100} value={summary.timePercent}/><span>{Math.floor(summary.timePercent)}%</span></label></div><div className="home-cycle-stats"><div><button className="text-button" onClick={()=>onPool('task',{cycle:cycle.id})}>本轮待办 {summary.tasks.length} 项</button><div className="home-state-totals">{Object.entries(STATUS).map(([key,label])=><button className={`pill ${key}`} key={key} onClick={()=>onPool('task',{cycle:cycle.id,status:key})}>{label} {summary.counts[key]}</button>)}</div></div><div className="home-week-totals"><button onClick={()=>onPool('assignment',{cycle:cycle.id,status:'done'})}>周任务完成 <strong>{summary.weekDone} / {summary.weeks.length}</strong></button><button onClick={()=>onPool('assignment',{cycle:cycle.id,schedule:'none'})}>待安排周任务 <strong>{summary.unscheduled}</strong></button></div></div></>:<p className="home-empty">可到 12 周计划选择已有周期，或<button className="text-button" onClick={()=>onCreate('cycle',{start_date:today})}>创建周期</button>。</p>}</section>
 {menu&&createPortal(<div className="home-action-menu" onKeyDown={e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();const buttons=Array.from(e.currentTarget.querySelectorAll('button')),index=buttons.indexOf(document.activeElement as HTMLButtonElement);buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}else if(e.key==='Tab')setMenu(null);}} role="menu" aria-label={`管理${menu.item.title}`} style={{left:menu.left,top:menu.top}}><button role="menuitem" onClick={()=>{onEdit(menu.item.kind,menu.item.id);setMenu(null);}}>编辑</button><button className="danger" role="menuitem" onClick={()=>{onDelete(menu.item.kind,menu.item.id,menu.item.title);setMenu(null);}}>删除</button></div>,document.body)}</div>;
}
