import { describe,it,expect } from 'vitest';
import { EMPTY, categoryTotals, type Data, type TimeEntry } from './model';
import { applyLinkedCategory, validCategory, linkedGoalCategory } from './timeCategories';
import { prepareRow } from './batch';
const data:Data={...EMPTY,tasks:[{id:'t',annual_goal_id:'a',cycle_id:null,cycle_goal_id:null,project_id:null,title:'待办',status:'todo',due_date:null,created_at:''}],assignments:[{id:'w',task_id:'t',cycle_id:null,commitment:'周任务',status:'todo',review:'',created_at:''}],dayTasks:[{id:'d',assignment_id:'w',task_id:'t',project_id:null,date:'2026-10-02',title:'日任务',status:'todo',recurrence_id:null,scheduled_start_at:null,scheduled_end_at:null,scheduled_category_id:null,created_at:''}],categories:[{id:'fixed',name:'学习',color:'#123456',created_at:'',kind:'fixed',active:1},{id:'goal',name:'2026 · 方向 · 目标',color:'#112233',created_at:'',kind:'goal',annual_goal_id:'a',goal_year:2026,active:1},{id:'old',name:'写作',color:'#334455',created_at:'',kind:'legacy',active:0},{id:'deleted',name:'旧目标',color:'#556677',created_at:'',kind:'goal',active:0,annual_goal_id:null}]};
describe('时间分类',()=>{
 it('只允许有效分类，新建不接受历史分类，编辑可保留原分类',()=>{expect(validCategory(data,'fixed')).toBe(true);expect(validCategory(data,'goal')).toBe(true);expect(validCategory(data,'old')).toBe(false);expect(validCategory(data,'deleted')).toBe(false);expect(validCategory(data,'old','old')).toBe(true);expect(validCategory(data,'missing','missing')).toBe(false);});
 it('关联日任务带入目标，周任务和待办的关联不改变',()=>{const values={day_task_id:'d'};expect(applyLinkedCategory(data,'entry',values).category_id).toBe('goal');expect(data.dayTasks[0].assignment_id).toBe('w');});
 it('无目标关联不猜测，删除目标分类不带入',()=>{expect(applyLinkedCategory(data,'entry',{day_task_id:'missing'})).toEqual({day_task_id:'missing'});expect(linkedGoalCategory({...data,categories:data.categories.filter(c=>c.id!=='goal')},'entry',{day_task_id:'d'})).toBeUndefined();});
 it('手动分类不因改选关联任务被覆盖，可显式使用关联目标',()=>{const values={day_task_id:'d',category_id:'fixed',__category_manual:'1'};expect(applyLinkedCategory(data,'entry',values).category_id).toBe('fixed');expect(applyLinkedCategory(data,'entry',values,true).category_id).toBe('goal');});
 it('没有具体时间的日任务不隐式要求填写时间',()=>{expect(applyLinkedCategory(data,'dayTask',{assignment_id:'w'}).category_id).toBeUndefined();expect(applyLinkedCategory(data,'dayTask',{assignment_id:'w',start:'16:00'}).category_id).toBe('goal');});
 it('批量新增拒绝历史分类，也允许不填时间',()=>{expect(()=>prepareRow('dayTask',{date:'2026-10-02',title:'任务',start:'16:00',end:'17:00',category_id:'old'},data)).toThrow('有效的固定类别或年度目标');expect(prepareRow('dayTask',{date:'2026-10-02',title:'任务'},data).values.scheduled_category_id).toBeNull();});
 it('跨午夜统计保留固定、工作和历史分类全部用时',()=>{const entry=(category_id:string,start:string,end:string):TimeEntry=>({id:category_id,title:'',day_task_id:null,project_id:null,task_id:null,created_at:'',category_id,start_at:new Date(start).toISOString(),end_at:new Date(end).toISOString()});const entries=[entry('fixed','2026-10-01T23:00:00','2026-10-02T01:00:00'),entry('goal','2026-10-02T01:00:00','2026-10-02T02:00:00'),entry('old','2026-10-02T02:00:00','2026-10-02T02:30:00')];const totals=categoryTotals(entries,data.categories,'2026-10-02','2026-10-03');expect(totals.total).toBe(150);expect(totals.rows.map(r=>r.minutes)).toEqual([60,60,30]);});
});
